USE [NTNXDB]
GO

SET ANSI_PADDING ON

GO

CREATE CLUSTERED INDEX [ClusteredIndex-NTNXDB] ON [dbo].[table001]
(
[Current Time] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

GO