WHILE (1=1)
BEGIN
    INSERT table008 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table008 VALUES('Flow','Era', SYSDATETIME())
    INSERT table008 VALUES('Calm','Objects', SYSDATETIME())
    INSERT table008 VALUES('Files','Volumes', SYSDATETIME())
    INSERT table008 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table008 VALUES('Flow','Era', SYSDATETIME())
    INSERT table008 VALUES('Calm','Objects', SYSDATETIME())
    INSERT table008 VALUES('Files','Volumes', SYSDATETIME())
    INSERT table008 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table008 VALUES('Flow','Era', SYSDATETIME())
    INSERT table008 VALUES('Calm','Objects', SYSDATETIME())
    INSERT table008 VALUES('Files','Volumes', SYSDATETIME())
    INSERT table008 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table008 VALUES('Flow','Era', SYSDATETIME())
    INSERT table008 VALUES('Calm','Objects', SYSDATETIME())
	INSERT table008 VALUES('Files','Volumes', SYSDATETIME())
    INSERT table008 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table008 VALUES('Flow','Era', SYSDATETIME())
    INSERT table008 VALUES('Calm','Objects', SYSDATETIME())
    INSERT table008 VALUES('Files','Volumes', SYSDATETIME())
END