WHILE (1=1)
BEGIN
    INSERT table005 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table005 VALUES('Flow','Era', SYSDATETIME())
    INSERT table005 VALUES('Calm','Objects', SYSDATETIME())
    INSERT table005 VALUES('Files','Volumes', SYSDATETIME())
    INSERT table005 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table005 VALUES('Flow','Era', SYSDATETIME())
    INSERT table005 VALUES('Calm','Objects', SYSDATETIME())
    INSERT table005 VALUES('Files','Volumes', SYSDATETIME())
    INSERT table005 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table005 VALUES('Flow','Era', SYSDATETIME())
    INSERT table005 VALUES('Calm','Objects', SYSDATETIME())
    INSERT table005 VALUES('Files','Volumes', SYSDATETIME())
    INSERT table005 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table005 VALUES('Flow','Era', SYSDATETIME())
    INSERT table005 VALUES('Calm','Objects', SYSDATETIME())
	INSERT table005 VALUES('Files','Volumes', SYSDATETIME())
    INSERT table005 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table005 VALUES('Flow','Era', SYSDATETIME())
    INSERT table005 VALUES('Calm','Objects', SYSDATETIME())
    INSERT table005 VALUES('Files','Volumes', SYSDATETIME())
END