WHILE (1=1)
BEGIN
    INSERT table010 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table010 VALUES('Flow','Era', SYSDATETIME())
    INSERT table010 VALUES('Calm','Objects', SYSDATETIME())
    INSERT table010 VALUES('Files','Volumes', SYSDATETIME())
    INSERT table010 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table010 VALUES('Flow','Era', SYSDATETIME())
    INSERT table010 VALUES('Calm','Objects', SYSDATETIME())
    INSERT table010 VALUES('Files','Volumes', SYSDATETIME())
    INSERT table010 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table010 VALUES('Flow','Era', SYSDATETIME())
    INSERT table010 VALUES('Calm','Objects', SYSDATETIME())
    INSERT table010 VALUES('Files','Volumes', SYSDATETIME())
    INSERT table010 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table010 VALUES('Flow','Era', SYSDATETIME())
    INSERT table010 VALUES('Calm','Objects', SYSDATETIME())
	INSERT table010 VALUES('Files','Volumes', SYSDATETIME())
    INSERT table010 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table010 VALUES('Flow','Era', SYSDATETIME())
    INSERT table010 VALUES('Calm','Objects', SYSDATETIME())
    INSERT table010 VALUES('Files','Volumes', SYSDATETIME())
END