WHILE (1=1)
BEGIN
    INSERT table001 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table001 VALUES('Flow','Era', SYSDATETIME())
    INSERT table001 VALUES('Calm','Objects', SYSDATETIME())
    INSERT table001 VALUES('Files','Volumes', SYSDATETIME())
    INSERT table001 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table001 VALUES('Flow','Era', SYSDATETIME())
    INSERT table001 VALUES('Calm','Objects', SYSDATETIME())
    INSERT table001 VALUES('Files','Volumes', SYSDATETIME())
    INSERT table001 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table001 VALUES('Flow','Era', SYSDATETIME())
    INSERT table001 VALUES('Calm','Objects', SYSDATETIME())
    INSERT table001 VALUES('Files','Volumes', SYSDATETIME())
    INSERT table001 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table001 VALUES('Flow','Era', SYSDATETIME())
    INSERT table001 VALUES('Calm','Objects', SYSDATETIME())
	INSERT table001 VALUES('Files','Volumes', SYSDATETIME())
    INSERT table001 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table001 VALUES('Flow','Era', SYSDATETIME())
    INSERT table001 VALUES('Calm','Objects', SYSDATETIME())
    INSERT table001 VALUES('Files','Volumes', SYSDATETIME())
END