WHILE (1=1)
BEGIN
    INSERT table003 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table003 VALUES('Flow','Era', SYSDATETIME())
    INSERT table003 VALUES('Calm','Objects', SYSDATETIME())
    INSERT table003 VALUES('Files','Volumes', SYSDATETIME())
    INSERT table003 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table003 VALUES('Flow','Era', SYSDATETIME())
    INSERT table003 VALUES('Calm','Objects', SYSDATETIME())
    INSERT table003 VALUES('Files','Volumes', SYSDATETIME())
    INSERT table003 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table003 VALUES('Flow','Era', SYSDATETIME())
    INSERT table003 VALUES('Calm','Objects', SYSDATETIME())
    INSERT table003 VALUES('Files','Volumes', SYSDATETIME())
    INSERT table003 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table003 VALUES('Flow','Era', SYSDATETIME())
    INSERT table003 VALUES('Calm','Objects', SYSDATETIME())
	INSERT table003 VALUES('Files','Volumes', SYSDATETIME())
    INSERT table003 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table003 VALUES('Flow','Era', SYSDATETIME())
    INSERT table003 VALUES('Calm','Objects', SYSDATETIME())
    INSERT table003 VALUES('Files','Volumes', SYSDATETIME())
END