WHILE (1=1)
BEGIN
    INSERT table004 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table004 VALUES('Flow','Era', SYSDATETIME())
    INSERT table004 VALUES('Calm','Objects', SYSDATETIME())
    INSERT table004 VALUES('Files','Volumes', SYSDATETIME())
    INSERT table004 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table004 VALUES('Flow','Era', SYSDATETIME())
    INSERT table004 VALUES('Calm','Objects', SYSDATETIME())
    INSERT table004 VALUES('Files','Volumes', SYSDATETIME())
    INSERT table004 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table004 VALUES('Flow','Era', SYSDATETIME())
    INSERT table004 VALUES('Calm','Objects', SYSDATETIME())
    INSERT table004 VALUES('Files','Volumes', SYSDATETIME())
    INSERT table004 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table004 VALUES('Flow','Era', SYSDATETIME())
    INSERT table004 VALUES('Calm','Objects', SYSDATETIME())
	INSERT table004 VALUES('Files','Volumes', SYSDATETIME())
    INSERT table004 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table004 VALUES('Flow','Era', SYSDATETIME())
    INSERT table004 VALUES('Calm','Objects', SYSDATETIME())
    INSERT table004 VALUES('Files','Volumes', SYSDATETIME())
END