WHILE (1=1)
BEGIN
    INSERT table002 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table002 VALUES('Flow','Era', SYSDATETIME())
    INSERT table002 VALUES('Calm','Objects', SYSDATETIME())
    INSERT table002 VALUES('Files','Volumes', SYSDATETIME())
    INSERT table002 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table002 VALUES('Flow','Era', SYSDATETIME())
    INSERT table002 VALUES('Calm','Objects', SYSDATETIME())
    INSERT table002 VALUES('Files','Volumes', SYSDATETIME())
    INSERT table002 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table002 VALUES('Flow','Era', SYSDATETIME())
    INSERT table002 VALUES('Calm','Objects', SYSDATETIME())
    INSERT table002 VALUES('Files','Volumes', SYSDATETIME())
    INSERT table002 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table002 VALUES('Flow','Era', SYSDATETIME())
    INSERT table002 VALUES('Calm','Objects', SYSDATETIME())
	INSERT table002 VALUES('Files','Volumes', SYSDATETIME())
    INSERT table002 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table002 VALUES('Flow','Era', SYSDATETIME())
    INSERT table002 VALUES('Calm','Objects', SYSDATETIME())
    INSERT table002 VALUES('Files','Volumes', SYSDATETIME())
END