WHILE (1=1)
BEGIN
    INSERT table009 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table009 VALUES('Flow','Era', SYSDATETIME())
    INSERT table009 VALUES('Calm','Objects', SYSDATETIME())
    INSERT table009 VALUES('Files','Volumes', SYSDATETIME())
    INSERT table009 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table009 VALUES('Flow','Era', SYSDATETIME())
    INSERT table009 VALUES('Calm','Objects', SYSDATETIME())
    INSERT table009 VALUES('Files','Volumes', SYSDATETIME())
    INSERT table009 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table009 VALUES('Flow','Era', SYSDATETIME())
    INSERT table009 VALUES('Calm','Objects', SYSDATETIME())
    INSERT table009 VALUES('Files','Volumes', SYSDATETIME())
    INSERT table009 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table009 VALUES('Flow','Era', SYSDATETIME())
    INSERT table009 VALUES('Calm','Objects', SYSDATETIME())
	INSERT table009 VALUES('Files','Volumes', SYSDATETIME())
    INSERT table009 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table009 VALUES('Flow','Era', SYSDATETIME())
    INSERT table009 VALUES('Calm','Objects', SYSDATETIME())
    INSERT table009 VALUES('Files','Volumes', SYSDATETIME())
END