WHILE (1=1)
BEGIN
    INSERT table006 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table006 VALUES('Flow','Era', SYSDATETIME())
    INSERT table006 VALUES('Calm','Objects', SYSDATETIME())
    INSERT table006 VALUES('Files','Volumes', SYSDATETIME())
    INSERT table006 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table006 VALUES('Flow','Era', SYSDATETIME())
    INSERT table006 VALUES('Calm','Objects', SYSDATETIME())
    INSERT table006 VALUES('Files','Volumes', SYSDATETIME())
    INSERT table006 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table006 VALUES('Flow','Era', SYSDATETIME())
    INSERT table006 VALUES('Calm','Objects', SYSDATETIME())
    INSERT table006 VALUES('Files','Volumes', SYSDATETIME())
    INSERT table006 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table006 VALUES('Flow','Era', SYSDATETIME())
    INSERT table006 VALUES('Calm','Objects', SYSDATETIME())
	INSERT table006 VALUES('Files','Volumes', SYSDATETIME())
    INSERT table006 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table006 VALUES('Flow','Era', SYSDATETIME())
    INSERT table006 VALUES('Calm','Objects', SYSDATETIME())
    INSERT table006 VALUES('Files','Volumes', SYSDATETIME())
END