WHILE (1=1)
BEGIN
    INSERT table007 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table007 VALUES('Flow','Era', SYSDATETIME())
    INSERT table007 VALUES('Calm','Objects', SYSDATETIME())
    INSERT table007 VALUES('Files','Volumes', SYSDATETIME())
    INSERT table007 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table007 VALUES('Flow','Era', SYSDATETIME())
    INSERT table007 VALUES('Calm','Objects', SYSDATETIME())
    INSERT table007 VALUES('Files','Volumes', SYSDATETIME())
    INSERT table007 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table007 VALUES('Flow','Era', SYSDATETIME())
    INSERT table007 VALUES('Calm','Objects', SYSDATETIME())
    INSERT table007 VALUES('Files','Volumes', SYSDATETIME())
    INSERT table007 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table007 VALUES('Flow','Era', SYSDATETIME())
    INSERT table007 VALUES('Calm','Objects', SYSDATETIME())
	INSERT table007 VALUES('Files','Volumes', SYSDATETIME())
    INSERT table007 VALUES('PrismPro','Karbon', SYSDATETIME())
    INSERT table007 VALUES('Flow','Era', SYSDATETIME())
    INSERT table007 VALUES('Calm','Objects', SYSDATETIME())
    INSERT table007 VALUES('Files','Volumes', SYSDATETIME())
END